Just a rellookin of readme
lmachens/diablo4.th.gl pull request #31
Opened 2023-06-21 23:14 UTC by NoNameTrademark

Just a more attractive makeover  of readme

2023-06-24 06:13 UTC, lmachens commented
Thx! I will come back to this in about 2 weeks ( on vacation right now)

2023-07-06 19:06 UTC, lmachens requested changes
Good job! I like the look and feel, but there are some smaller issues.

2023-07-06 19:06 UTC, lmachens commented on README.md
> +[JQuery-url]: https://jquery.com
There are some links which are not used like svelte or jquery

2023-07-06 19:06 UTC, lmachens commented on README.md
> +_[❤️](https://github.com/NoNameTrademark)_
Would it be ok for you to remove this? You would be visible as contributor and in the commit history

2023-07-06 19:06 UTC, lmachens commented on README.md
> +- [ ] iscovery of nodes for multiple characters
```suggestion
- [x] Discovery of nodes for multiple characters
```

2023-07-06 19:06 UTC, lmachens commented on README.md
> +- [ ] Customizable appearance, including icon sizes
Icon size is already customizable

2023-07-06 19:06 UTC, lmachens commented on README.md
> +[![GitHub manifest version (path)][Version-shield]][Version-url]
This won't work, because I didn't use the releases feature on GitHub

2023-07-06 19:06 UTC, lmachens commented on README.md
> +[![MIT License][license-shield]][license-url]
I think these shields are looking great, but you already see the same information in the about section on the repository page. I think it would be nice to have shields for additional information

2023-07-06 19:22 UTC, NoNameTrademark commented on README.md
> +_[❤️](https://github.com/NoNameTrademark)_
Yes it was just for my fork..

2023-07-06 19:58 UTC, NoNameTrademark commented on README.md
> +[![GitHub manifest version (path)][Version-shield]][Version-url]
need to link it to overwolf/manifest.json

2023-07-06 20:13 UTC, NoNameTrademark commented on README.md
> +[![MIT License][license-shield]][license-url]
Contributor and fork are optional. I would keep the version and the stars, and see if we can add the number of downloads on overwolf.

2023-07-31 19:07 UTC, merged